version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somepass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  db_data: {}
